// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cont_frechet_cpp
double cont_frechet_cpp(const NumericMatrix& P, const NumericMatrix& Q);
RcppExport SEXP _thermoclustr_cont_frechet_cpp(SEXP PSEXP, SEXP QSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Q(QSEXP);
    rcpp_result_gen = Rcpp::wrap(cont_frechet_cpp(P, Q));
    return rcpp_result_gen;
END_RCPP
}
// discrete_frechet_cpp
double discrete_frechet_cpp(NumericMatrix A, NumericMatrix B);
RcppExport SEXP _thermoclustr_discrete_frechet_cpp(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(discrete_frechet_cpp(A, B));
    return rcpp_result_gen;
END_RCPP
}
// pairwise_cont_frechet_cpp
NumericMatrix pairwise_cont_frechet_cpp(List mats);
RcppExport SEXP _thermoclustr_pairwise_cont_frechet_cpp(SEXP matsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mats(matsSEXP);
    rcpp_result_gen = Rcpp::wrap(pairwise_cont_frechet_cpp(mats));
    return rcpp_result_gen;
END_RCPP
}
// pairwise_discr_frechet_cpp
NumericMatrix pairwise_discr_frechet_cpp(List mats);
RcppExport SEXP _thermoclustr_pairwise_discr_frechet_cpp(SEXP matsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mats(matsSEXP);
    rcpp_result_gen = Rcpp::wrap(pairwise_discr_frechet_cpp(mats));
    return rcpp_result_gen;
END_RCPP
}
// hausdorff_cpp
double hausdorff_cpp(const NumericMatrix& P, const NumericMatrix& Q);
RcppExport SEXP _thermoclustr_hausdorff_cpp(SEXP PSEXP, SEXP QSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Q(QSEXP);
    rcpp_result_gen = Rcpp::wrap(hausdorff_cpp(P, Q));
    return rcpp_result_gen;
END_RCPP
}
// pairwise_hausdorff_cpp
NumericMatrix pairwise_hausdorff_cpp(List mats);
RcppExport SEXP _thermoclustr_pairwise_hausdorff_cpp(SEXP matsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mats(matsSEXP);
    rcpp_result_gen = Rcpp::wrap(pairwise_hausdorff_cpp(mats));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_thermoclustr_cont_frechet_cpp", (DL_FUNC) &_thermoclustr_cont_frechet_cpp, 2},
    {"_thermoclustr_discrete_frechet_cpp", (DL_FUNC) &_thermoclustr_discrete_frechet_cpp, 2},
    {"_thermoclustr_pairwise_cont_frechet_cpp", (DL_FUNC) &_thermoclustr_pairwise_cont_frechet_cpp, 1},
    {"_thermoclustr_pairwise_discr_frechet_cpp", (DL_FUNC) &_thermoclustr_pairwise_discr_frechet_cpp, 1},
    {"_thermoclustr_hausdorff_cpp", (DL_FUNC) &_thermoclustr_hausdorff_cpp, 2},
    {"_thermoclustr_pairwise_hausdorff_cpp", (DL_FUNC) &_thermoclustr_pairwise_hausdorff_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_thermoclustr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
