// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// hausdorff_rcpp
double hausdorff_rcpp(NumericMatrix P, NumericMatrix Q);
RcppExport SEXP _thermochron_hausdorff_rcpp(SEXP PSEXP, SEXP QSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type P(PSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Q(QSEXP);
    rcpp_result_gen = Rcpp::wrap(hausdorff_rcpp(P, Q));
    return rcpp_result_gen;
END_RCPP
}
// hausdorff_matrix_rcpp
NumericMatrix hausdorff_matrix_rcpp(List x_list);
RcppExport SEXP _thermochron_hausdorff_matrix_rcpp(SEXP x_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x_list(x_listSEXP);
    rcpp_result_gen = Rcpp::wrap(hausdorff_matrix_rcpp(x_list));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_thermochron_hausdorff_rcpp", (DL_FUNC) &_thermochron_hausdorff_rcpp, 2},
    {"_thermochron_hausdorff_matrix_rcpp", (DL_FUNC) &_thermochron_hausdorff_matrix_rcpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_thermochron(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
